### ISSUE TITLE
NPE during load testing

### ISSUE THREAD

**Issue by etki** [mrniko/redisson#253]
Hi.
I'm relatively new to java, so sorry if i say something stupid.
When i'm storming my server with 50 concurrent requests using AB, i'm getting NPE during some channel negotiating (as i guess). The following line (CommandDecoder:267):

```java
    private MultiDecoder<Object> messageDecoder(CommandData<Object, Object> data, List<Object> parts) {
        if (data == null) {
            if (Arrays.asList("subscribe", "psubscribe", "punsubscribe", "unsubscribe").contains(parts.get(0))) {
                String channelName = (String) parts.get(1);
                return channels.get(channelName).getCommand().getReplayMultiDecoder(); // <<<<
            } else if (parts.get(0).equals("message")) {
```

results in null pointer exception:

```
2015-30-09 18:28:11.271 [nioEventLoopGroup-2-2] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:425) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [backend-phone-service-0.1.0-shaded-cp.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.NullPointerException: null
	at org.redisson.client.handler.CommandDecoder.messageDecoder(CommandDecoder.java:267) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	at org.redisson.client.handler.CommandDecoder.decodeMulti(CommandDecoder.java:202) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:189) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:97) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370) ~[backend-phone-service-0.1.0-shaded-cp.jar:na]
	... 18 common frames omitted
```

I'm not 100% sure where does this problem originate from, but i can tell that those requests use Redisson for inter-process locks and fetching/updating two string sets.

I'm using Redisson 2.1.3 against dockerized Redis 3.0.2 (the standard docker library image)

upd: debugger told me that client has received null for hannels.get() for `redisson__lock__channel__{lock:pn:phone-number:79219767095}`, which, i guess, means trouble with lock.

**Comment by mnouh** [comment]
I'm getting the same issue. See below code snippet, accessing the client with 10+ threads:
```
        RLock lock = redisson.getLock(LOCK_KEY+ip);
		lock.lock();
		try {
			//business logic
		} finally {
			lock.unlock();
		}
```

```
Exception:
2015-10-08 23:46:36 WARN  DefaultChannelPipeline:151 - [nioEventLoopGroup-2-1] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
```

**Comment by mrniko** [comment]
please bring to me your test code

**Comment by etki** [comment]
@mrniko i can't expose my project sources, but i'll try to make a minimal sample on this weekend

**Comment by dugshnay** [comment]
We also were seeing this in production when we went to 2.1.3 last week. It had the effect of hanging the threads and we reverted to 1.3.1 a couple days ago. I can provide a small test project. This will *sometimes*, but not every time, reproduce this NPE issue (you can see it in the logs). What it will do every time is walk its way into a deadlock on subscribe/unsubscribe. I run two tests. One with 400 threads, which seems to always be fine, but when I bump that to 600 threads it crosses some threshold and ends deadlocked (or perhaps so many threads waiting on tryAcquire so long my latch expires). I don't really believe it's just a latch expiration issue in the test, that just allows me to get out of the test. The test outputs the state of the threads and you can see how many are blocked.

Am I able to send a zipped tar of the project? Or do I need to break it down to just the source files and upload them here?

**Comment by mrniko** [comment]
you can send me it by email: abracham.mitchell@gmail.com

**Comment by dugshnay** [comment]
Thank you. I've sent it. I wanted to also clarify that I do not know if the NPE and the deadlock issue I mentioned are related or two separate issues.

**Comment by mrniko** [comment]
@dugshnay Thanks for your work! This test is really helpful. I just reproduced this issue, will work on it

**Comment by mrniko** [comment]
Redis can send reply twice on SUBSCRIBE/UNSUBSCRIBE commands. So I'm just skipping them.

Fixed. Please check too.

**Comment by etki** [comment]
@mrniko sorry i still don't have time for checking.
Thank you for great support
