### ISSUE TITLE
Two serious issues

### ISSUE THREAD

**Issue by lianghaijian** [mrniko/redisson#41]
1.Sentinel not support auth password.（I have solve this problem）
2.When redis sentinel occur failover，redisson can not failover to new master automatic。

**Comment by prarthanb** [comment]
I am facing same issue. One of the sentinels in my config is down and i can not start server as redisson always try to connect the last one in config.

**Comment by mrniko** [comment]
@prarthanb 
> always try to connect the last one in config

and not the server which has down? it's never connects to sentinel which has down?

**Comment by prarthanb** [comment]
Always connects to last one even if it is down. And never retries other sentinels in the config.

**Comment by mrniko** [comment]
ok, i'll fix it

**Comment by jackygurui** [comment]
Having sentinel failing over to slave but redisson refuse to reconnect to new master issue:

I have two nodes: both runs sentinel and redis server on default ports. When I send a DEBUG SEGFAULT to the master I get the following:

On slave node:
10.211.55.23:26379> SUBSCRIBE +switch-master
Reading messages... (press Ctrl-C to quit)
1) "subscribe"
2) "+switch-master"
3) (integer) 1
1) "message"
2) "+switch-master"
3) "redis 10.211.55.24 6379 10.211.55.23 6379"

On master node:
10.211.55.24:26379> SUBSCRIBE +sdown
Reading messages... (press Ctrl-C to quit)
1) "subscribe"
2) "+sdown"
3) (integer) 1
1) "message"
2) "+sdown"
3) "master redis 10.211.55.24 6379"
1) "message"
2) "+sdown"
3) "slave 10.211.55.24:6379 10.211.55.24 6379 @ redis 10.211.55.23 6379"

However on the redisson output I am getting "WARN org.redisson.connection.SentinelConnectionManager:onSlaveDown(180) - Invalid message: master redis 10.211.55.24 6379 from Sentinel localhost:26379 " warning message but the connections is not re-establishing.

**Comment by mrniko** [comment]
@jackygurui I fixed your problem. Please check

**Comment by jackygurui** [comment]
Hi @mrniko 

Thanks for getting back so quick. I have tried the same scenario with the latest master code, upon having sent DEBUG SEGFAULT to the master, I am still getting an error message saying it can't connect to the already dead node. It has not failed over to the new master.

20:06:09,240  WARN org.redisson.connection.RoundRobinLoadBalancer:nextConnection(197) - Can't connect to /10.211.55.24:6379, trying next connection!
20:06:11,440  WARN org.redisson.connection.RoundRobinLoadBalancer:nextConnection(197) - Can't connect to /10.211.55.24:6379, trying next connection!
20:06:13,640  WARN org.redisson.connection.RoundRobinLoadBalancer:nextConnection(197) - Can't connect to /10.211.55.24:6379, trying next connection!
20:06:15,839  WARN org.redisson.connection.RoundRobinLoadBalancer:nextConnection(197) - Can't connect to /10.211.55.24:6379, trying next connection!

**Comment by mrniko** [comment]
could you decrease the timeout and try again? because after timeout i see the master is in the game and requests go forward

**Comment by mrniko** [comment]
@jackygurui please check it again

**Comment by mrniko** [comment]
@prarthanb 
> I am facing same issue. One of the sentinels in my config is down and i can not start server as redisson always try to connect the last one in config. 

So the problem appears during redisson start only, right?

**Comment by mrniko** [comment]
@prarthanb i fixed this case. please check too

**Comment by prarthanb** [comment]
thanks.

**Comment by jackygurui** [comment]
@mrniko Thanks. I think it is working now.
