### ISSUE TITLE
RLock trylock blocks forever

### ISSUE THREAD

**Issue by arnabguptadev** [mrniko/redisson#543]
Found this in 2.2.16, seems like this was not around in 2.2.10. But still verifying.

When tryLock is called with 0 wait time, the thread blocks forever. I took a thread dump and it looks like the stack pasted below. 

A note on the environment: We are running this against an Elasticache cluster in AWS and accessing from 4 EC2 instances. We have seen a lot of command timeouts. I am not sure if that is some way leading to this.

"pool-4-thread-5" #86 prio=5 os_prio=0 tid=0x00007f15ca23f800 nid=0xcd4 waiting for monitor entry [0x00007f15b90e5000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.redisson.pubsub.PublishSubscribe.subscribe(PublishSubscribe.java:53)
	- waiting to lock <0x00000000dd405ea0> (a org.redisson.pubsub.LockPubSub)
	at org.redisson.pubsub.LockPubSub.subscribe(LockPubSub.java:22)
	at org.redisson.RedissonLock.subscribe(RedissonLock.java:311)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:264)
	at c.v.w.utils.caching.redis.RedisLock.tryLock(RedisLock.java:36)
	at c.v.w.utils.caching.LeasedLock.tryLock(LeasedLock.java:19)
	at c.v.w.eventprocessor.core.service.impl.JobProcessor.getProcessingLock(JobProcessor.java:130)
	at c.v.w.eventprocessor.core.service.impl.JobProcessor.access$000(JobProcessor.java:47)
	at c.v.w.webscan.eventprocessor.core.service.impl.JobProcessor$Processor.execute(JobProcessor.java:193)
	at c.v.w.service.integration.core.DataContextAwareTask.run(DataContextAwareTask.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
Please try 2.2.17 version too. pubsub issue during lock usage was fixed there.

**Comment by arnabguptadev** [comment]
Will definitely do. Maven central had 2.2.16. 17 is next up. Thanks!

**Comment by arnabguptadev** [comment]
I am not sure if environment is partly to blame. But when we run with 2.2.10, things work fine. Once we moved to 2.2.17 we start seeing tons of Command execution timeout (even after we bump it up to 15 seconds). Think for now, we will just move back to 2.2.10.

org.redisson.client.RedisTimeoutException: Command execution timeout for ******.use1.cache.amazonaws.com/*.*.*.*:6379
	at org.redisson.client.RedisConnection.await(RedisConnection.java:128) ~[redisson-2.2.17.jar!/:na]
	at org.redisson.client.RedisConnection.sync(RedisConnection.java:147) ~[redisson-2.2.17.jar!/:na]
	at org.redisson.connection.ElasticacheConnectionManager$1.run(ElasticacheConnectionManager.java:134) ~[redisson-2.2.17.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:126) [netty-common-4.0.37.Final.jar!/:4.0.37.Final]

**Comment by mrniko** [comment]
Could you try 2.2.15 version? just want to know from which version it starts?

**Comment by mrniko** [comment]
Also please take note that starting 2.2.11 it has performance improvements which leads to more requests pressure for your environment.

**Comment by mrniko** [comment]
Could you also provide your test code?

**Comment by mrniko** [comment]
Also try to set `subscriptionsPerConnection` = 1 with 2.2.17 version

**Comment by anilmuthineni** [comment]
I also see this issue in 2.2.16
We use the following config
new Config().useSingleServer()
    .setAddress(s"$hostName:$port")
    .setTimeout(10000)
    .setConnectTimeout(5000)
    .setRetryAttempts(3)
    .setRetryInterval(2000)
    .setConnectionPoolSize(500)

I found that org.redisson.pubsub.PublishSubscribe#41 blocks inside synchronized block, not allowing any more progress in subscribe() and unsubscribe() calls.

It works fine is I use a different org.redisson.RedissonClient instance for each getLock and tryLock calls. It is not progressing if I use the same org.redisson.RedissonClient instance  for all locking and unlocking.

**Comment by mrniko** [comment]
@anilmuthineni 
> I found that org.redisson.pubsub.PublishSubscribe#41 

confirm 2.2.16 has such bug. But 2.2.17 should work

**Comment by mrniko** [comment]
@arnabguptadev 

ElasticacheConnectionManager.java:134 it seems like it can't connect to one of your elasticache node

**Comment by anilmuthineni** [comment]
It's not fixed in 2.2.17, even with subscriptionsPerConnection = 1. However I am not able to catch where it is blocking in 2.2.17, and as before, tryLock is not able to progress into the synchronized block at org.redisson.pubsub.PublishSubscribe#53

2.2.10 is working fine. Does 2.2.10 support redis 3.x? (Not able to find documentation on it)

**Comment by mrniko** [comment]
@anilmuthineni 
Could you give your test case?

**Comment by mrniko** [comment]
I rewrote pubsub management. Could you try it from [new_pubsub](https://github.com/mrniko/redisson/tree/new_pubsub) branch?

**Comment by mediarss** [comment]
I have the exact same issue. tried 2.2.17, 2.2.16, 2.2.15
I was passing 1L into tryLock as the waitTime

**Comment by mrniko** [comment]
@mediarss Could you try version from https://github.com/mrniko/redisson/tree/new_pubsub ?

**Comment by mrniko** [comment]
Fix has been merged

**Comment by mrniko** [comment]
2.2.18 version has out! please give it a try

**Comment by mrniko** [comment]
Fixed in 2.2.21 version

**Comment by arnabguptadev** [comment]
Sorry, I was out of the loop for some time. I should have updated this thread before. Anyway, here's the status. We are still seeing issues - currently we are on version 22. There are two issues 

1. tryLock never returns (the thread is not BLOCKED as before, but in a WAITING state) - here's the thread dump:

"pool-6-thread-1" #71 prio=5 os_prio=0 tid=0x00007f707d31a800 nid=0xda3 waiting on condition [0x00007f70df099000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c32db118> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.Semaphore.acquireUninterruptibly(Semaphore.java:335)
	at org.redisson.pubsub.PublishSubscribe.subscribe(PublishSubscribe.java:57)
	at org.redisson.pubsub.LockPubSub.subscribe(LockPubSub.java:22)
	at org.redisson.RedissonLock.subscribe(RedissonLock.java:314)
	at org.redisson.RedissonLock.tryLock(RedissonLock.java:267)

2. A call to BlockingQueue poll also enters a wait state forever even when a timeout is specified (5 seconds). I think it is waiting for redis response since the call is of course not synchronous - as I do not see our classes in stack trace.

"nioEventLoopGroup-2-4" #42 prio=10 os_prio=0 tid=0x00007f707e6d7800 nid=0xd8b waiting on condition [0x00007f70dd44d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c32daf68> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.Semaphore.acquireUninterruptibly(Semaphore.java:335)
	at org.redisson.pubsub.PublishSubscribe.unsubscribe(PublishSubscribe.java:38)
	at org.redisson.RedissonLock.unsubscribe(RedissonLock.java:318)
	at org.redisson.RedissonLock$4.operationComplete(RedissonLock.java:273)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:427)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:111)
	at org.redisson.pubsub.PublishSubscribe$1.onStatus(PublishSubscribe.java:104)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:69)
	at org.redisson.client.handler.CommandDecoder.handleMultiResult(CommandDecoder.java:344)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:317)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:286)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:110)

**Comment by mrniko** [comment]
@arnabguptadev Fixed. Please try `2.2.x` branch

**Comment by arnabguptadev** [comment]
@mrniko: Thanks a lot! Will let you know. So we are on 2.2.22. You are suggesting 2.2.24?

**Comment by mrniko** [comment]
@arnabguptadev I suggest you to make a build of `2.2.24-SNAPSHOT` from `2.2.x` branch and try it before I release it. Could you do it?

**Comment by arnabguptadev** [comment]
Will do. Thanks!

**Comment by arnabguptadev** [comment]
Hi @mrniko - Seems the fix is working so far. I am doing more tests. Will keep you updated. Are you putting this in maven central?

**Comment by mrniko** [comment]
I'm glad to know it! I'm gonna put this in maven central right after you finish your tests :)

**Comment by arnabguptadev** [comment]
@mrniko: Looks great now. We are all set with out tests. No issues. Please put this in maven central so we can pick up in our regular build process. Thanks a lot! Let me know if I should close this.

**Comment by mrniko** [comment]
Cool. Finally fixed!
